### PR TITLE
chore: add challenges

### PR DESCRIPTION
**Pull request by taramakage**

### CODE REVIEW

**Review by eviebbang — APPROVED** [review]

**Comment by giansalex** [comment]
@taramakage What should be the title format of the issue to claim a challenge?

**Comment by taramakage** [comment]
> @taramakage What should be the title format of the issue to claim a challenge?

Please refer to the title of [gon-evidence#500](https://github.com/game-of-nfts/gon-evidence/issues/500)

**Comment by giansalex** [comment]
Hi @taramakage, CHALLENGES were not included in this distribution, where will they be included?

image
 
Additionally, these challenges (mainly C2) are caused by a malicious contract attack (packets loop).
It's like giving rewards for fixing reported bugs.

**Comment by taramakage** [comment]
They are a part of tasks completion pool

**Comment by giansalex** [comment]
> They are a part of tasks award

thanks for the clarification

**Pull request merged**
